using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TFramework.Singleton;
using TFramework.Utils;

namespace SoftLiu_ServerIOCSharp.Misc
{
    public class MiscManager : AutoGeneratedSingleton<MiscManager>, IDisposable
    {

        public const string pathContentTypeJson = "../../Misc/ContentType.json";

        private Dictionary<string, string> m_ContentTypeDic = null;
        public Dictionary<string, string> ContentTypeDic { get { return m_ContentTypeDic; } }
        public MiscManager()
        {
            m_ContentTypeDic = new Dictionary<string, string>();
        }

        public void Init()
        {
            using (StreamReader sr = new StreamReader(File.OpenRead(pathContentTypeJson)))
            {
                string read = sr.ReadToEnd();
                m_ContentTypeDic = JsonUtils.Instance.JsonToObject<Dictionary<string, string>>(read);
            }
        }

        public void Dispose()
        {
            m_ContentTypeDic = null;
        }
    }
}
