// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/UserInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.TFramework {

  /// <summary>Holder for reflection information generated from proto/UserInfo.proto</summary>
  public static partial class UserInfoReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/UserInfo.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserInfoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRwcm90by9Vc2VySW5mby5wcm90bxIKVEZyYW1ld29yayJ7CghVc2VySW5m",
            "bxIOCgZ1c2VySWQYASABKAQSEAoIdXNlck5hbWUYAiABKAkSJgoKdXNlckdl",
            "bmRlchgDIAEoDjISLlRGcmFtZXdvcmsuR2VuZGVyEg8KB3VzZXJBZ2UYBCAB",
            "KA0SFAoMdXNlclBob25lTnVtGAUgASgJKjUKBkdlbmRlchIMCghNYWxlVHlw",
            "ZRAAEg4KCkZlbWFsZVR5cGUQARINCglPdGhlclR5cGUQAkIdqgIaR29vZ2xl",
            "LlByb3RvYnVmLlRGcmFtZXdvcmtiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.TFramework.Gender), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.TFramework.UserInfo), global::Google.Protobuf.TFramework.UserInfo.Parser, new[]{ "UserId", "UserName", "UserGender", "UserAge", "UserPhoneNum" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Gender {
    [pbr::OriginalName("MaleType")] MaleType = 0,
    [pbr::OriginalName("FemaleType")] FemaleType = 1,
    [pbr::OriginalName("OtherType")] OtherType = 2,
  }

  #endregion

  #region Messages
  public sealed partial class UserInfo : pb::IMessage<UserInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UserInfo> _parser = new pb::MessageParser<UserInfo>(() => new UserInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UserInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.TFramework.UserInfoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserInfo(UserInfo other) : this() {
      userId_ = other.userId_;
      userName_ = other.userName_;
      userGender_ = other.userGender_;
      userAge_ = other.userAge_;
      userPhoneNum_ = other.userPhoneNum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UserInfo Clone() {
      return new UserInfo(this);
    }

    /// <summary>Field number for the "userId" field.</summary>
    public const int UserIdFieldNumber = 1;
    private ulong userId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong UserId {
      get { return userId_; }
      set {
        userId_ = value;
      }
    }

    /// <summary>Field number for the "userName" field.</summary>
    public const int UserNameFieldNumber = 2;
    private string userName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserName {
      get { return userName_; }
      set {
        userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "userGender" field.</summary>
    public const int UserGenderFieldNumber = 3;
    private global::Google.Protobuf.TFramework.Gender userGender_ = global::Google.Protobuf.TFramework.Gender.MaleType;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.TFramework.Gender UserGender {
      get { return userGender_; }
      set {
        userGender_ = value;
      }
    }

    /// <summary>Field number for the "userAge" field.</summary>
    public const int UserAgeFieldNumber = 4;
    private uint userAge_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint UserAge {
      get { return userAge_; }
      set {
        userAge_ = value;
      }
    }

    /// <summary>Field number for the "userPhoneNum" field.</summary>
    public const int UserPhoneNumFieldNumber = 5;
    private string userPhoneNum_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserPhoneNum {
      get { return userPhoneNum_; }
      set {
        userPhoneNum_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UserInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UserInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserId != other.UserId) return false;
      if (UserName != other.UserName) return false;
      if (UserGender != other.UserGender) return false;
      if (UserAge != other.UserAge) return false;
      if (UserPhoneNum != other.UserPhoneNum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserId != 0UL) hash ^= UserId.GetHashCode();
      if (UserName.Length != 0) hash ^= UserName.GetHashCode();
      if (UserGender != global::Google.Protobuf.TFramework.Gender.MaleType) hash ^= UserGender.GetHashCode();
      if (UserAge != 0) hash ^= UserAge.GetHashCode();
      if (UserPhoneNum.Length != 0) hash ^= UserPhoneNum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(UserId);
      }
      if (UserName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserName);
      }
      if (UserGender != global::Google.Protobuf.TFramework.Gender.MaleType) {
        output.WriteRawTag(24);
        output.WriteEnum((int) UserGender);
      }
      if (UserAge != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(UserAge);
      }
      if (UserPhoneNum.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(UserPhoneNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(UserId);
      }
      if (UserName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(UserName);
      }
      if (UserGender != global::Google.Protobuf.TFramework.Gender.MaleType) {
        output.WriteRawTag(24);
        output.WriteEnum((int) UserGender);
      }
      if (UserAge != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(UserAge);
      }
      if (UserPhoneNum.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(UserPhoneNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UserId);
      }
      if (UserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
      }
      if (UserGender != global::Google.Protobuf.TFramework.Gender.MaleType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UserGender);
      }
      if (UserAge != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UserAge);
      }
      if (UserPhoneNum.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserPhoneNum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UserInfo other) {
      if (other == null) {
        return;
      }
      if (other.UserId != 0UL) {
        UserId = other.UserId;
      }
      if (other.UserName.Length != 0) {
        UserName = other.UserName;
      }
      if (other.UserGender != global::Google.Protobuf.TFramework.Gender.MaleType) {
        UserGender = other.UserGender;
      }
      if (other.UserAge != 0) {
        UserAge = other.UserAge;
      }
      if (other.UserPhoneNum.Length != 0) {
        UserPhoneNum = other.UserPhoneNum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UserId = input.ReadUInt64();
            break;
          }
          case 18: {
            UserName = input.ReadString();
            break;
          }
          case 24: {
            UserGender = (global::Google.Protobuf.TFramework.Gender) input.ReadEnum();
            break;
          }
          case 32: {
            UserAge = input.ReadUInt32();
            break;
          }
          case 42: {
            UserPhoneNum = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UserId = input.ReadUInt64();
            break;
          }
          case 18: {
            UserName = input.ReadString();
            break;
          }
          case 24: {
            UserGender = (global::Google.Protobuf.TFramework.Gender) input.ReadEnum();
            break;
          }
          case 32: {
            UserAge = input.ReadUInt32();
            break;
          }
          case 42: {
            UserPhoneNum = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
