using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TFramework.Singleton;
using TFramework.Utils;

namespace SoftLiu_ServerIOCSharp.SocketData
{
    public class SocketManager : AutoGeneratedSingleton<SocketManager>
    {

        public List<SocketProtocolData> ProtocolDatas { get; private set; }
        public void SetProtocolDatas(List<SocketProtocolData> datas)
        {
            ProtocolDatas = datas;
        }
    }
}
